# Generated by Django 5.1.3 on 2024-11-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometrics',
            name='user',
        ),
        migrations.AddField(
            model_name='biometrics',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='height',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='maintenance_calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='biometrics',
            name='weight',
            field=models.FloatField(),
        ),
    ]
